apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k5r7coosm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k5r7coosm-nodejs 
  name: k5r7coosm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: k5r7coosm-nodejs 
